import { prisma } from './db'

const OFFICIAL_SERVERS = [
  {
    name: 'GitHub',
    slug: 'github',
    description: 'Search repos, manage issues, read files, list PRs and commits',
    icon: 'github',
    url: 'https://api.githubcopilot.com/mcp/',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 12,
  },
  {
    name: 'Filesystem',
    slug: 'filesystem',
    description: 'Read, write, search files and list directories on the server',
    icon: 'folder-open',
    url: 'http://localhost:3001/mcp',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Web Fetch',
    slug: 'webfetch',
    description: 'Fetch and extract content from any web page or URL',
    icon: 'globe',
    url: '',
    category: 'research',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 3,
  },
  {
    name: 'Web Search',
    slug: 'websearch',
    description: 'Google search, news search, and fetch web pages via Serper API',
    icon: 'globe',
    url: '',
    category: 'research',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 3,
  },
  {
    name: 'Database',
    slug: 'database',
    description: 'Query SQL databases, list tables, describe schemas, explain queries',
    icon: 'database',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 6,
  },
  {
    name: 'Slack',
    slug: 'slack',
    description: 'Send messages, list channels, search messages, manage users',
    icon: 'message-square',
    url: '',
    category: 'communication',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 8,
  },
  {
    name: 'Git',
    slug: 'git',
    description: 'Git operations — clone, commit, push, pull, diff, log, and branch management',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 10,
  },
  {
    name: 'Memory',
    slug: 'memory',
    description: 'Persistent knowledge graph for storing and retrieving structured data across sessions',
    icon: 'database',
    url: '',
    category: 'general',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 6,
  },
  {
    name: 'Sequential Thinking',
    slug: 'sequential-thinking',
    description: 'Step-by-step reasoning and problem decomposition for complex tasks',
    icon: 'terminal',
    url: '',
    category: 'general',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 1,
  },
  {
    name: 'Time',
    slug: 'time',
    description: 'Get current time, convert timezones, and calculate date differences',
    icon: 'terminal',
    url: '',
    category: 'general',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 3,
  },
  {
    name: 'Everything',
    slug: 'everything',
    description: 'Reference MCP server for testing — implements all MCP features and capabilities',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 4,
  },
  {
    name: 'Google Maps',
    slug: 'google-maps',
    description: 'Search places, get directions, geocode addresses, and explore nearby locations',
    icon: 'globe',
    url: '',
    category: 'research',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Brave Search',
    slug: 'brave-search',
    description: 'Privacy-focused web and local search powered by Brave Search API',
    icon: 'globe',
    url: '',
    category: 'research',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 2,
  },
  {
    name: 'Puppeteer',
    slug: 'puppeteer',
    description: 'Browser automation — navigate pages, take screenshots, click elements, fill forms',
    icon: 'globe',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 8,
  },
  {
    name: 'PostgreSQL',
    slug: 'postgres',
    description: 'Connect to PostgreSQL databases, run queries, inspect schemas and tables',
    icon: 'database',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 4,
  },
  {
    name: 'Sentry',
    slug: 'sentry',
    description: 'Query error reports, view issues, and analyze crash data from Sentry',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Google Drive',
    slug: 'google-drive',
    description: 'Search, read, and manage files in Google Drive',
    icon: 'folder-open',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 4,
  },
  {
    name: 'Linear',
    slug: 'linear',
    description: 'Manage issues, projects, and teams in Linear project management',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 6,
  },
  {
    name: 'Notion',
    slug: 'notion',
    description: 'Search pages, read content, create and update pages in Notion workspaces',
    icon: 'terminal',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 8,
  },
  {
    name: 'Jira',
    slug: 'jira',
    description: 'Create and search issues, manage sprints, and track projects in Jira',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 7,
  },
  {
    name: 'Confluence',
    slug: 'confluence',
    description: 'Search, read, and create pages in Atlassian Confluence wikis',
    icon: 'terminal',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Discord',
    slug: 'discord',
    description: 'Send messages, manage channels, and interact with Discord servers',
    icon: 'message-square',
    url: '',
    category: 'communication',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 6,
  },
  {
    name: 'Telegram',
    slug: 'telegram',
    description: 'Send messages, manage chats, and interact with Telegram bots',
    icon: 'message-square',
    url: '',
    category: 'communication',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Email (SMTP)',
    slug: 'email-smtp',
    description: 'Send emails, manage drafts, and read inbox via SMTP/IMAP',
    icon: 'message-square',
    url: '',
    category: 'communication',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 4,
  },
  {
    name: 'Stripe',
    slug: 'stripe',
    description: 'Manage customers, payments, subscriptions, and invoices via Stripe API',
    icon: 'terminal',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 10,
  },
  {
    name: 'Shopify',
    slug: 'shopify',
    description: 'Manage products, orders, customers, and inventory in Shopify stores',
    icon: 'terminal',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 8,
  },
  {
    name: 'Figma',
    slug: 'figma',
    description: 'Read designs, list files, extract components and styles from Figma',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'AWS',
    slug: 'aws',
    description: 'Manage S3 buckets, Lambda functions, EC2 instances, and other AWS services',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 12,
  },
  {
    name: 'Docker',
    slug: 'docker',
    description: 'List containers, manage images, view logs, and control Docker environments',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 8,
  },
  {
    name: 'Kubernetes',
    slug: 'kubernetes',
    description: 'Manage pods, deployments, services, and namespaces in Kubernetes clusters',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 10,
  },
  {
    name: 'MySQL',
    slug: 'mysql',
    description: 'Connect to MySQL databases, run queries, inspect schemas and tables',
    icon: 'database',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 4,
  },
  {
    name: 'MongoDB',
    slug: 'mongodb',
    description: 'Query collections, insert documents, and manage MongoDB databases',
    icon: 'database',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 6,
  },
  {
    name: 'Redis',
    slug: 'redis',
    description: 'Get and set keys, manage data structures, and inspect Redis instances',
    icon: 'database',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Twilio',
    slug: 'twilio',
    description: 'Send SMS, make calls, and manage phone numbers via Twilio API',
    icon: 'message-square',
    url: '',
    category: 'communication',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Cloudflare',
    slug: 'cloudflare',
    description: 'Manage DNS records, Workers, KV storage, and Cloudflare settings',
    icon: 'globe',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 8,
  },
  {
    name: 'YouTube',
    slug: 'youtube',
    description: 'Search videos, get transcripts, channel info, and video metadata',
    icon: 'globe',
    url: '',
    category: 'research',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 4,
  },
  {
    name: 'Twitter / X',
    slug: 'twitter',
    description: 'Post tweets, search timeline, read mentions, and manage Twitter accounts',
    icon: 'message-square',
    url: '',
    category: 'communication',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 6,
  },
  {
    name: 'Vercel',
    slug: 'vercel',
    description: 'Manage deployments, domains, environment variables, and projects on Vercel',
    icon: 'terminal',
    url: '',
    category: 'dev',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 7,
  },
  {
    name: 'Supabase',
    slug: 'supabase',
    description: 'Manage tables, run queries, handle auth, and interact with Supabase projects',
    icon: 'database',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 8,
  },
  {
    name: 'OpenAPI',
    slug: 'openapi',
    description: 'Load any OpenAPI spec and call its endpoints as MCP tools',
    icon: 'globe',
    url: '',
    category: 'general',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 1,
  },
  {
    name: 'HubSpot',
    slug: 'hubspot',
    description: 'Manage contacts, deals, companies, and tickets in HubSpot CRM',
    icon: 'terminal',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 8,
  },
  {
    name: 'Airtable',
    slug: 'airtable',
    description: 'Read, create, update, and delete records in Airtable bases',
    icon: 'database',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Google Calendar',
    slug: 'google-calendar',
    description: 'List events, create meetings, check availability, and manage calendars',
    icon: 'terminal',
    url: '',
    category: 'general',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 5,
  },
  {
    name: 'Google Sheets',
    slug: 'google-sheets',
    description: 'Read, write, and manage spreadsheets in Google Sheets',
    icon: 'database',
    url: '',
    category: 'data',
    isOfficial: true,
    authType: 'none',
    authConfig: null,
    toolCount: 6,
  },
]

export async function seedMcpServers() {
  for (const server of OFFICIAL_SERVERS) {
    await prisma.mcpServer.upsert({
      where: { slug: server.slug },
      update: {
        name: server.name,
        description: server.description,
        icon: server.icon,
        category: server.category,
        authType: server.authType,
        authConfig: server.authConfig,
        toolCount: server.toolCount,
      },
      create: server,
    })
  }

  console.log(`[mcp] Seeded ${OFFICIAL_SERVERS.length} MCP servers`)
}
